run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt
    - goimports
    - revive
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc

linters-settings:
  goimports:
    local-prefixes: github.com/kdubb1337/runpod-cli
  revive:
    rules:
      - name: var-naming
      - name: package-comments
      - name: exported
        arguments: [checkPrivateReceivers, disableStutteringCheck]

issues:
  exclude-rules:
    - path: _test\.go
      linters: [errcheck, prealloc]
